export const data = [
  {
    thingCode: "A_11002853_110",
    thingName: "总进线1",
    baseCode: "A29",
    baseName: "电",
    baseUnit: "kWh",
    attrName: "峰用电",
    attrCode: "A29_peakhh",
    allDosage: 464.1,
    totalPrice: 232.0,
    totalPriceRatio: 16.2,
    standardRatio: null,
    realityRatio: 18.5,
    uintPrice: 0.5,
    peakValleyDosageReqs: [
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703257200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703253600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703250000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703246400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703242800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703239200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703235600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703232000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703228400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703224800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703221200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703217600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703214000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703210400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703206800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11002853_110",
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: "kWh",
        dosage: 464.1,
        ts: "1703203200000",
        uintPrice: 0.5,
        totalPrice: 232.0,
        sort: 1
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703199600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703196000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703192400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703188800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703185200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703181600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703178000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703174400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      }
    ],
    sort: 1
  },
  {
    thingCode: "A_11002853_110",
    thingName: "总进线1",
    baseCode: "A29",
    baseName: "电",
    baseUnit: "kWh",
    attrName: "尖用电",
    attrCode: "A29_rushhh",
    allDosage: 92.8,
    totalPrice: 27.8,
    totalPriceRatio: 1.9,
    standardRatio: null,
    realityRatio: 3.7,
    uintPrice: 0.3,
    peakValleyDosageReqs: [
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703257200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703253600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703250000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703246400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703242800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703239200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703235600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703232000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703228400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703224800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703221200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703217600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703214000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703210400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11002853_110",
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: "kWh",
        dosage: 92.8,
        ts: "1703206800000",
        uintPrice: 0.3,
        totalPrice: 27.8,
        sort: 2
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703203200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703199600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703196000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703192400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703188800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703185200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703181600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703178000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703174400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      }
    ],
    sort: 2
  },
  {
    thingCode: "A_11002853_110",
    thingName: "总进线1",
    baseCode: "A29",
    baseName: "电",
    baseUnit: "kWh",
    attrName: "谷用电",
    attrCode: "A29_valleyhh",
    allDosage: 1950.0,
    totalPrice: 1170.0,
    totalPriceRatio: 81.8,
    standardRatio: null,
    realityRatio: 77.8,
    uintPrice: 0.6,
    peakValleyDosageReqs: [
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703257200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703253600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703250000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703246400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703242800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703239200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703235600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703232000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703228400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703224800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703221200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703217600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703214000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703210400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703206800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703203200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11002853_110",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 451.9,
        ts: "1703199600000",
        uintPrice: 0.6,
        totalPrice: 271.1,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11002853_110",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 266.3,
        ts: "1703196000000",
        uintPrice: 0.6,
        totalPrice: 159.8,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11002853_110",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 225.9,
        ts: "1703192400000",
        uintPrice: 0.6,
        totalPrice: 135.6,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11002853_110",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 205.3,
        ts: "1703188800000",
        uintPrice: 0.6,
        totalPrice: 123.2,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11002853_110",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 198.8,
        ts: "1703185200000",
        uintPrice: 0.6,
        totalPrice: 119.3,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11002853_110",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 206.3,
        ts: "1703181600000",
        uintPrice: 0.6,
        totalPrice: 123.8,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11002853_110",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 196.9,
        ts: "1703178000000",
        uintPrice: 0.6,
        totalPrice: 118.1,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11002853_110",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 198.8,
        ts: "1703174400000",
        uintPrice: 0.6,
        totalPrice: 119.3,
        sort: 3
      }
    ],
    sort: 3
  },
  {
    thingCode: "A_11002853_110",
    thingName: "总进线1",
    baseCode: "A29",
    baseName: "电",
    baseUnit: "kWh",
    attrName: "电总用量",
    attrCode: "A29",
    allDosage: 2506.9,
    totalPrice: 1429.8,
    totalPriceRatio: null,
    standardRatio: null,
    realityRatio: 100,
    uintPrice: null,
    peakValleyDosageReqs: [
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703257200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703253600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703250000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703246400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703242800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703239200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703235600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703232000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703228400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703224800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703221200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703217600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703214000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703210400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 92.8,
        ts: "1703206800000",
        uintPrice: null,
        totalPrice: 27.8,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 464.1,
        ts: "1703203200000",
        uintPrice: null,
        totalPrice: 232.0,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 451.9,
        ts: "1703199600000",
        uintPrice: null,
        totalPrice: 271.1,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 266.3,
        ts: "1703196000000",
        uintPrice: null,
        totalPrice: 159.8,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 225.9,
        ts: "1703192400000",
        uintPrice: null,
        totalPrice: 135.6,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 205.3,
        ts: "1703188800000",
        uintPrice: null,
        totalPrice: 123.2,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 198.8,
        ts: "1703185200000",
        uintPrice: null,
        totalPrice: 119.3,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 206.3,
        ts: "1703181600000",
        uintPrice: null,
        totalPrice: 123.8,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 196.9,
        ts: "1703178000000",
        uintPrice: null,
        totalPrice: 118.1,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 198.8,
        ts: "1703174400000",
        uintPrice: null,
        totalPrice: 119.3,
        sort: null
      }
    ],
    sort: 99
  },

  {
    thingCode: "A_11003457_142",
    thingName: "总进线3",
    baseCode: "A29",
    baseName: "电",
    baseUnit: "kWh",
    attrName: "峰用电",
    attrCode: "A29_peakhh",
    allDosage: 830.6,
    totalPrice: 415.3,
    totalPriceRatio: 15.0,
    standardRatio: null,
    realityRatio: 17.1,
    uintPrice: 0.5,
    peakValleyDosageReqs: [
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703257200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703253600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703250000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703246400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703242800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703239200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703235600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703232000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703228400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703224800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703221200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703217600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703214000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703210400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703206800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11003457_142",
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: "kWh",
        dosage: 830.6,
        ts: "1703203200000",
        uintPrice: 0.5,
        totalPrice: 415.3,
        sort: 1
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703199600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703196000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703192400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703188800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703185200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703181600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703178000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_peakhh",
        attrName: "峰用电",
        uint: null,
        dosage: null,
        ts: "1703174400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      }
    ],
    sort: 1
  },
  {
    thingCode: "A_11003457_142",
    thingName: "总进线3",
    baseCode: "A29",
    baseName: "电",
    baseUnit: "kWh",
    attrName: "尖用电",
    attrCode: "A29_rushhh",
    allDosage: 216.9,
    totalPrice: 65.1,
    totalPriceRatio: 2.4,
    standardRatio: null,
    realityRatio: 4.5,
    uintPrice: 0.3,
    peakValleyDosageReqs: [
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703257200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703253600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703250000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703246400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703242800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703239200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703235600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703232000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703228400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703224800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703221200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703217600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703214000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703210400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11003457_142",
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: "kWh",
        dosage: 216.9,
        ts: "1703206800000",
        uintPrice: 0.3,
        totalPrice: 65.1,
        sort: 2
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703203200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703199600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703196000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703192400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703188800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703185200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703181600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703178000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_rushhh",
        attrName: "尖用电",
        uint: null,
        dosage: null,
        ts: "1703174400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      }
    ],
    sort: 2
  },
  {
    thingCode: "A_11003457_142",
    thingName: "总进线3",
    baseCode: "A29",
    baseName: "电",
    baseUnit: "kWh",
    attrName: "谷用电",
    attrCode: "A29_valleyhh",
    allDosage: 3813.1,
    totalPrice: 2287.9,
    totalPriceRatio: 82.6,
    standardRatio: null,
    realityRatio: 78.4,
    uintPrice: 0.6,
    peakValleyDosageReqs: [
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703257200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703253600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703250000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703246400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703242800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703239200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703235600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703232000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703228400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703224800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703221200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703217600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703214000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703210400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703206800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: null,
        baseName: null,
        thingCode: null,
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: null,
        dosage: null,
        ts: "1703203200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11003457_142",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 687.5,
        ts: "1703199600000",
        uintPrice: 0.6,
        totalPrice: 412.5,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11003457_142",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 535.6,
        ts: "1703196000000",
        uintPrice: 0.6,
        totalPrice: 321.4,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11003457_142",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 474.4,
        ts: "1703192400000",
        uintPrice: 0.6,
        totalPrice: 284.6,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11003457_142",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 439.4,
        ts: "1703188800000",
        uintPrice: 0.6,
        totalPrice: 263.6,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11003457_142",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 418.1,
        ts: "1703185200000",
        uintPrice: 0.6,
        totalPrice: 250.9,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11003457_142",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 417.5,
        ts: "1703181600000",
        uintPrice: 0.6,
        totalPrice: 250.5,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11003457_142",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 412.5,
        ts: "1703178000000",
        uintPrice: 0.6,
        totalPrice: 247.5,
        sort: 3
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: "A_11003457_142",
        attrCode: "A29_valleyhh",
        attrName: "谷用电",
        uint: "kWh",
        dosage: 428.1,
        ts: "1703174400000",
        uintPrice: 0.6,
        totalPrice: 256.9,
        sort: 3
      }
    ],
    sort: 3
  },
  {
    thingCode: "A_11003457_142",
    thingName: "总进线3",
    baseCode: "A29",
    baseName: "电",
    baseUnit: "kWh",
    attrName: "电总用量",
    attrCode: "A29",
    allDosage: 4860.6,
    totalPrice: 2768.3,
    totalPriceRatio: null,
    standardRatio: null,
    realityRatio: 100,
    uintPrice: null,
    peakValleyDosageReqs: [
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703257200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703253600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703250000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703246400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703242800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703239200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703235600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703232000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703228400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703224800000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703221200000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703217600000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703214000000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: null,
        ts: "1703210400000",
        uintPrice: null,
        totalPrice: null,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 216.9,
        ts: "1703206800000",
        uintPrice: null,
        totalPrice: 65.1,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 830.6,
        ts: "1703203200000",
        uintPrice: null,
        totalPrice: 415.3,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 687.5,
        ts: "1703199600000",
        uintPrice: null,
        totalPrice: 412.5,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 535.6,
        ts: "1703196000000",
        uintPrice: null,
        totalPrice: 321.4,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 474.4,
        ts: "1703192400000",
        uintPrice: null,
        totalPrice: 284.6,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 439.4,
        ts: "1703188800000",
        uintPrice: null,
        totalPrice: 263.6,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 418.1,
        ts: "1703185200000",
        uintPrice: null,
        totalPrice: 250.9,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 417.5,
        ts: "1703181600000",
        uintPrice: null,
        totalPrice: 250.5,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 412.5,
        ts: "1703178000000",
        uintPrice: null,
        totalPrice: 247.5,
        sort: null
      },
      {
        baseCode: "A29",
        baseName: "电",
        thingCode: null,
        attrCode: "电",
        attrName: "A29",
        uint: "kWh",
        dosage: 428.1,
        ts: "1703174400000",
        uintPrice: null,
        totalPrice: 256.9,
        sort: null
      }
    ],
    sort: 99
  }
];
